export class CallbackType {
    /** @type {"AddCommentCallback"} */
    static AddCommentCallback = "AddCommentCallback";
    /** @type {"AddEditableRegionCallback"} */
    static AddEditableRegionCallback = "AddEditableRegionCallback";
    /** @type {"AddFootnoteCallback"} */
    static AddFootnoteCallback = "AddFootnoteCallback";
    /** @type {"AddSubTextPartCallback"} */
    static AddSubTextPartCallback = "AddSubTextPartCallback";
    /** @type {"BarcodeCallback"} */
    static BarcodeCallback = "BarcodeCallback";
    /** @type {"Callback"} */
    static Callback = "Callback";
    /** @type {"CannotTrackChangeCallback"} */
    static CannotTrackChangeCallback = "CannotTrackChangeCallback";
    /** @type {"ChartCallback"} */
    static ChartCallback = "ChartCallback";
    /** @type {"CheckFormFieldCallback"} */
    static CheckFormFieldCallback = "CheckFormFieldCallback";
    /** @type {"ClipboardDataTransferAbortedCallback"} */
    static ClipboardDataTransferAbortedCallback = "ClipboardDataTransferAbortedCallback";
    /** @type {"ClipboardDataTransferCompleteCallback"} */
    static ClipboardDataTransferCompleteCallback = "ClipboardDataTransferCompleteCallback";
    /** @type {"ClipboardDataTransferProgressCallback"} */
    static ClipboardDataTransferProgressCallback = "ClipboardDataTransferProgressCallback";
    /** @type {"ClipboardDataTransferStartCallback"} */
    static ClipboardDataTransferStartCallback = "ClipboardDataTransferStartCallback";
    /** @type {"ClipboardModeChangedCallback"} */
    static ClipboardModeChangedCallback = "ClipboardModeChangedCallback";
    /** @type {"CommentEventCallback"} */
    static CommentEventCallback = "CommentEventCallback";
    /** @type {"ContextMenuEventCallback"} */
    static ContextMenuEventCallback = "ContextMenuEventCallback";
    /** @type {"ContextMenuItemClickHandler"} */
    static ContextMenuItemClickHandler = "ContextMenuItemClickHandler";
    /** @type {"DateFormFieldCallback"} */
    static DateFormFieldCallback = "DateFormFieldCallback";
    /** @type {"DocumentLinkCallback"} */
    static DocumentLinkCallback = "DocumentLinkCallback";
    /** @type {"DocumentLoadedCallback"} */
    static DocumentLoadedCallback = "DocumentLoadedCallback";
    /** @type {"DrawingCallback"} */
    static DrawingCallback = "DrawingCallback";
    /** @type {"EditableRegionCallback"} */
    static EditableRegionCallback = "EditableRegionCallback";
    /** @type {"EmptyRequestCallback"} */
    static EmptyRequestCallback = "EmptyRequestCallback";
    /** @type {"ErrorCallback"} */
    static ErrorCallback = "ErrorCallback";
    /** @type {"EventCallback"} */
    static EventCallback = "EventCallback";
    /** @type {"FileDroppedCallback"} */
    static FileDroppedCallback = "FileDroppedCallback";
    /** @type {"FootnoteCallback"} */
    static FootnoteCallback = "FootnoteCallback";
    /** @type {"ForEachCallback"} */
    static ForEachCallback = "ForEachCallback";
    /** @type {"FrameCallback"} */
    static FrameCallback = "FrameCallback";
    /** @type {"GetDictionaryListCallback"} */
    static GetDictionaryListCallback = "GetDictionaryListCallback";
    /** @type {"GetUserDictionaryInfoCallback"} */
    static GetUserDictionaryInfoCallback = "GetUserDictionaryInfoCallback";
    /** @type {"HeaderFooterCallback"} */
    static HeaderFooterCallback = "HeaderFooterCallback";
    /** @type {"HypertextLinkClickedCallback"} */
    static HypertextLinkClickedCallback = "HypertextLinkClickedCallback";
    /** @type {"HyphenateWordCallback"} */
    static HyphenateWordCallback = "HyphenateWordCallback";
    /** @type {"ImageCallback"} */
    static ImageCallback = "ImageCallback";
    /** @type {"InputPositionChangedCallback"} */
    static InputPositionChangedCallback = "InputPositionChangedCallback";
    /** @type {"LoadDocumentCallback"} */
    static LoadDocumentCallback = "LoadDocumentCallback";
    /** @type {"ReconnectionFailedCallback"} */
    static ReconnectionFailedCallback = "ReconnectionFailedCallback";
    /** @type {"RequestActivationStateCallback"} */
    static RequestActivationStateCallback = "RequestActivationStateCallback";
    /** @type {"RequestApplicationFieldCallback"} */
    static RequestApplicationFieldCallback = "RequestApplicationFieldCallback";
    /** @type {"RequestAutoBaselineCallback"} */
    static RequestAutoBaselineCallback = "RequestAutoBaselineCallback";
    /** @type {"RequestBarcodeAlignmentCallback"} */
    static RequestBarcodeAlignmentCallback = "RequestBarcodeAlignmentCallback";
    /** @type {"RequestBarcodeFrameCallback"} */
    static RequestBarcodeFrameCallback = "RequestBarcodeFrameCallback";
    /** @type {"RequestBarcodeTextAlignmentCallback"} */
    static RequestBarcodeTextAlignmentCallback = "RequestBarcodeTextAlignmentCallback";
    /** @type {"RequestBarcodeTypeCallback"} */
    static RequestBarcodeTypeCallback = "RequestBarcodeTypeCallback";
    /** @type {"RequestBooleanCallback"} */
    static RequestBooleanCallback = "RequestBooleanCallback";
    /** @type {"RequestCapitalsCallback"} */
    static RequestCapitalsCallback = "RequestCapitalsCallback";
    /** @type {"RequestCellFormatCallback"} */
    static RequestCellFormatCallback = "RequestCellFormatCallback";
    /** @type {"RequestChangeKindCallback"} */
    static RequestChangeKindCallback = "RequestChangeKindCallback";
    /** @type {"RequestCheckFormFieldCallback"} */
    static RequestCheckFormFieldCallback = "RequestCheckFormFieldCallback";
    /** @type {"RequestColorStringCallback"} */
    static RequestColorStringCallback = "RequestColorStringCallback";
    /** @type {"RequestCommentCallback"} */
    static RequestCommentCallback = "RequestCommentCallback";
    /** @type {"RequestCommentsCallback"} */
    static RequestCommentsCallback = "RequestCommentsCallback";
    /** @type {"RequestDateFormFieldCallback"} */
    static RequestDateFormFieldCallback = "RequestDateFormFieldCallback";
    /** @type {"RequestDirectionCallback"} */
    static RequestDirectionCallback = "RequestDirectionCallback";
    /** @type {"RequestDistancesCallback"} */
    static RequestDistancesCallback = "RequestDistancesCallback";
    /** @type {"RequestDocumentLinkCallback"} */
    static RequestDocumentLinkCallback = "RequestDocumentLinkCallback";
    /** @type {"RequestDocumentTargetCallback"} */
    static RequestDocumentTargetCallback = "RequestDocumentTargetCallback";
    /** @type {"RequestEditModeCallback"} */
    static RequestEditModeCallback = "RequestEditModeCallback";
    /** @type {"RequestEditableRegionsCallback"} */
    static RequestEditableRegionsCallback = "RequestEditableRegionsCallback";
    /** @type {"RequestFontUnderlineStyleCallback"} */
    static RequestFontUnderlineStyleCallback = "RequestFontUnderlineStyleCallback";
    /** @type {"RequestFormFieldCallback"} */
    static RequestFormFieldCallback = "RequestFormFieldCallback";
    /** @type {"RequestFormattingStyleCallback"} */
    static RequestFormattingStyleCallback = "RequestFormattingStyleCallback";
    /** @type {"RequestFormulaReferenceStyleCallback"} */
    static RequestFormulaReferenceStyleCallback = "RequestFormulaReferenceStyleCallback";
    /** @type {"RequestFrameBaseCallback"} */
    static RequestFrameBaseCallback = "RequestFrameBaseCallback";
    /** @type {"RequestFrameCallback"} */
    static RequestFrameCallback = "RequestFrameCallback";
    /** @type {"RequestFrameInsertionModeCallback"} */
    static RequestFrameInsertionModeCallback = "RequestFrameInsertionModeCallback";
    /** @type {"RequestFrameStyleCallback"} */
    static RequestFrameStyleCallback = "RequestFrameStyleCallback";
    /** @type {"RequestHeaderFooterCallback"} */
    static RequestHeaderFooterCallback = "RequestHeaderFooterCallback";
    /** @type {"RequestHeaderFooterTypeCallback"} */
    static RequestHeaderFooterTypeCallback = "RequestHeaderFooterTypeCallback";
    /** @type {"RequestHighlightModeCallback"} */
    static RequestHighlightModeCallback = "RequestHighlightModeCallback";
    /** @type {"RequestHorizontalAlignmentCallback"} */
    static RequestHorizontalAlignmentCallback = "RequestHorizontalAlignmentCallback";
    /** @type {"RequestHypertextLinkCallback"} */
    static RequestHypertextLinkCallback = "RequestHypertextLinkCallback";
    /** @type {"RequestImageCallback"} */
    static RequestImageCallback = "RequestImageCallback";
    /** @type {"RequestInlineStyleCallback"} */
    static RequestInlineStyleCallback = "RequestInlineStyleCallback";
    /** @type {"RequestJustificationCallback"} */
    static RequestJustificationCallback = "RequestJustificationCallback";
    /** @type {"RequestLineCallback"} */
    static RequestLineCallback = "RequestLineCallback";
    /** @type {"RequestListFormatCharacterCallback"} */
    static RequestListFormatCharacterCallback = "RequestListFormatCharacterCallback";
    /** @type {"RequestMeasuringUnitCallback"} */
    static RequestMeasuringUnitCallback = "RequestMeasuringUnitCallback";
    /** @type {"RequestMisspelledWordCallback"} */
    static RequestMisspelledWordCallback = "RequestMisspelledWordCallback";
    /** @type {"RequestNumberCallback"} */
    static RequestNumberCallback = "RequestNumberCallback";
    /** @type {"RequestNumberFormatCallback"} */
    static RequestNumberFormatCallback = "RequestNumberFormatCallback";
    /** @type {"RequestNumberFormatsCallback"} */
    static RequestNumberFormatsCallback = "RequestNumberFormatsCallback";
    /** @type {"RequestNumbersCallback"} */
    static RequestNumbersCallback = "RequestNumbersCallback";
    /** @type {"RequestObjectCallback"} */
    static RequestObjectCallback = "RequestObjectCallback";
    /** @type {"RequestPageCallback"} */
    static RequestPageCallback = "RequestPageCallback";
    /** @type {"RequestPageNumberFieldCallback"} */
    static RequestPageNumberFieldCallback = "RequestPageNumberFieldCallback";
    /** @type {"RequestPaperSizesCallback"} */
    static RequestPaperSizesCallback = "RequestPaperSizesCallback";
    /** @type {"RequestParagraphCallback"} */
    static RequestParagraphCallback = "RequestParagraphCallback";
    /** @type {"RequestParagraphFormatCallback"} */
    static RequestParagraphFormatCallback = "RequestParagraphFormatCallback";
    /** @type {"RequestParagraphStyleCallback"} */
    static RequestParagraphStyleCallback = "RequestParagraphStyleCallback";
    /** @type {"RequestPermanentControlCharsCallback"} */
    static RequestPermanentControlCharsCallback = "RequestPermanentControlCharsCallback";
    /** @type {"RequestPointCallback"} */
    static RequestPointCallback = "RequestPointCallback";
    /** @type {"RequestRectangleCallback"} */
    static RequestRectangleCallback = "RequestRectangleCallback";
    /** @type {"RequestRenderModeCallback"} */
    static RequestRenderModeCallback = "RequestRenderModeCallback";
    /** @type {"RequestRulerBarBorderStyleCallback"} */
    static RequestRulerBarBorderStyleCallback = "RequestRulerBarBorderStyleCallback";
    /** @type {"RequestRulerBarFormulaModeCallback"} */
    static RequestRulerBarFormulaModeCallback = "RequestRulerBarFormulaModeCallback";
    /** @type {"RequestRulerBarScaleUnitCallback"} */
    static RequestRulerBarScaleUnitCallback = "RequestRulerBarScaleUnitCallback";
    /** @type {"RequestSectionBreakKindCallback"} */
    static RequestSectionBreakKindCallback = "RequestSectionBreakKindCallback";
    /** @type {"RequestSectionCallback"} */
    static RequestSectionCallback = "RequestSectionCallback";
    /** @type {"RequestSelectionFormFieldCallback"} */
    static RequestSelectionFormFieldCallback = "RequestSelectionFormFieldCallback";
    /** @type {"RequestSignatureFieldCallback"} */
    static RequestSignatureFieldCallback = "RequestSignatureFieldCallback";
    /** @type {"RequestSignerDataCallback"} */
    static RequestSignerDataCallback = "RequestSignerDataCallback";
    /** @type {"RequestSizeCallback"} */
    static RequestSizeCallback = "RequestSizeCallback";
    /** @type {"RequestStringCallback"} */
    static RequestStringCallback = "RequestStringCallback";
    /** @type {"RequestStringsCallback"} */
    static RequestStringsCallback = "RequestStringsCallback";
    /** @type {"RequestSubTextPartCallback"} */
    static RequestSubTextPartCallback = "RequestSubTextPartCallback";
    /** @type {"RequestSubTextPartsCallback"} */
    static RequestSubTextPartsCallback = "RequestSubTextPartsCallback";
    /** @type {"RequestTabTypesCallback"} */
    static RequestTabTypesCallback = "RequestTabTypesCallback";
    /** @type {"RequestTableCallback"} */
    static RequestTableCallback = "RequestTableCallback";
    /** @type {"RequestTableCellCallback"} */
    static RequestTableCellCallback = "RequestTableCellCallback";
    /** @type {"RequestTableColumnCallback"} */
    static RequestTableColumnCallback = "RequestTableColumnCallback";
    /** @type {"RequestTableOfContentsCallback"} */
    static RequestTableOfContentsCallback = "RequestTableOfContentsCallback";
    /** @type {"RequestTableRowCallback"} */
    static RequestTableRowCallback = "RequestTableRowCallback";
    /** @type {"RequestTextCharCallback"} */
    static RequestTextCharCallback = "RequestTextCharCallback";
    /** @type {"RequestTextFieldCallback"} */
    static RequestTextFieldCallback = "RequestTextFieldCallback";
    /** @type {"RequestTextFieldInfoArrayCallback"} */
    static RequestTextFieldInfoArrayCallback = "RequestTextFieldInfoArrayCallback";
    /** @type {"RequestTextFieldsCallback"} */
    static RequestTextFieldsCallback = "RequestTextFieldsCallback";
    /** @type {"RequestTextFormFieldCallback"} */
    static RequestTextFormFieldCallback = "RequestTextFormFieldCallback";
    /** @type {"RequestTextFrameCallback"} */
    static RequestTextFrameCallback = "RequestTextFrameCallback";
    /** @type {"RequestTextPartCallback"} */
    static RequestTextPartCallback = "RequestTextPartCallback";
    /** @type {"RequestTextPartsCallback"} */
    static RequestTextPartsCallback = "RequestTextPartsCallback";
    /** @type {"RequestTextTypeCallback"} */
    static RequestTextTypeCallback = "RequestTextTypeCallback";
    /** @type {"RequestTrackedChangeCallback"} */
    static RequestTrackedChangeCallback = "RequestTrackedChangeCallback";
    /** @type {"RequestVerticalAlignmentCallback"} */
    static RequestVerticalAlignmentCallback = "RequestVerticalAlignmentCallback";
    /** @type {"RequestViewModeCallback"} */
    static RequestViewModeCallback = "RequestViewModeCallback";
    /** @type {"RibbonTabIndexChangedCallback"} */
    static RibbonTabIndexChangedCallback = "RibbonTabIndexChangedCallback";
    /** @type {"RibbonTabLoadedCallback"} */
    static RibbonTabLoadedCallback = "RibbonTabLoadedCallback";
    /** @type {"RibbonTabsLoadedCallback"} */
    static RibbonTabsLoadedCallback = "RibbonTabsLoadedCallback";
    /** @type {"SaveDocumentCallback"} */
    static SaveDocumentCallback = "SaveDocumentCallback";
    /** @type {"SaveDocumentResultCallback"} */
    static SaveDocumentResultCallback = "SaveDocumentResultCallback";
    /** @type {"SaveUserDictionaryCallback"} */
    static SaveUserDictionaryCallback = "SaveUserDictionaryCallback";
    /** @type {"SelectionFormFieldCallback"} */
    static SelectionFormFieldCallback = "SelectionFormFieldCallback";
    /** @type {"SideBarTypeRequestCallback"} */
    static SideBarTypeRequestCallback = "SideBarTypeRequestCallback";
    /** @type {"SignatureFieldCallback"} */
    static SignatureFieldCallback = "SignatureFieldCallback";
    /** @type {"SpellCheckTextCallback"} */
    static SpellCheckTextCallback = "SpellCheckTextCallback";
    /** @type {"SubTextPartCallback"} */
    static SubTextPartCallback = "SubTextPartCallback";
    /** @type {"TableCallback"} */
    static TableCallback = "TableCallback";
    /** @type {"TableOfContentsCallback"} */
    static TableOfContentsCallback = "TableOfContentsCallback";
    /** @type {"TextControlChangedCallback"} */
    static TextControlChangedCallback = "TextControlChangedCallback";
    /** @type {"TextControlLoadedCallback"} */
    static TextControlLoadedCallback = "TextControlLoadedCallback";
    /** @type {"TextDroppedCallback"} */
    static TextDroppedCallback = "TextDroppedCallback";
    /** @type {"TextFieldCallback"} */
    static TextFieldCallback = "TextFieldCallback";
    /** @type {"TextFormFieldCallback"} */
    static TextFormFieldCallback = "TextFormFieldCallback";
    /** @type {"TextFrameCallback"} */
    static TextFrameCallback = "TextFrameCallback";
    /** @type {"TextPastedCallback"} */
    static TextPastedCallback = "TextPastedCallback";
    /** @type {"TextViewLocationChangedCallback"} */
    static TextViewLocationChangedCallback = "TextViewLocationChangedCallback";
    /** @type {"TrackedChangeCallback"} */
    static TrackedChangeCallback = "TrackedChangeCallback";
    /** @type {"WebSocketClosedCallback"} */
    static WebSocketClosedCallback = "WebSocketClosedCallback";
    /** @type {"ZoomFactorChangedCallback"} */
    static ZoomFactorChangedCallback = "ZoomFactorChangedCallback";
}
