name: Node.js Package

on:
  push:
    branches:
    - develop
  workflow_dispatch:
  
env:
  AZURE_ARTIFACTS_FEED_URL: 'tfs.sinc.de/tfs/Intern/_packaging/SINC_Cases/npm/'
  AZURE_ARTIFACTS_USERNAME: 'bna'
  NODE_VERSION: 18

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://${{ env.AZURE_ARTIFACTS_FEED_URL }}registry/
          always-auth: true
          
      - name: Replace with appropriate .npmrc
        run: |
          echo "registry=${{ env.AZURE_ARTIFACTS_FEED_URL }}
          always-auth=true
          ; begin auth token
          ${{ env.AZURE_ARTIFACTS_FEED_URL }}registry/:username=${{ env.AZURE_ARTIFACTS_USERNAME }}
          ${{ env.AZURE_ARTIFACTS_FEED_URL }}registry/:_password=${{ secrets.AZURE_ARTIFACTS_BASE64_PAT }}
          ${{ env.AZURE_ARTIFACTS_FEED_URL }}registry/:email=npm requires email to be set but doesn't use the value
          ${{ env.AZURE_ARTIFACTS_FEED_URL }}:username=${{ env.AZURE_ARTIFACTS_USERNAME }}
          ${{ env.AZURE_ARTIFACTS_FEED_URL }}:_password=${{ secrets.AZURE_ARTIFACTS_BASE64_PAT }}
          ${{ env.AZURE_ARTIFACTS_FEED_URL }}:email=npm requires email to be set but doesn't use the value
          ; end auth token" > /home/runner/work/_temp/.npmrc
#      - run: yarn
#      - run: yarn publish      
      - run: npm ci
      - run: npm publish
