name: Publish package to GitHub Packages
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  github:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@sinc-gmbh'
      - name: Build Package
        run: |
          yarn install --immutable
          yarn run build
        working-directory: lib
      - name: Publish to GitHub Packages
        run: yarn npm publish --access public
        env:
          YARN_NPM_PUBLISH_REGISTRY: https://npm.pkg.github.com
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: lib
  npm:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Required for OIDC
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          scope: '@sinc-gmbh'
      - name: copy readme
        run: |
          cp README.md lib/README.md
      - name: Build Package
        run: |
          yarn install --immutable
          yarn run build
        working-directory: lib
      - name: Publish to npm
        run: NODE_AUTH_TOKEN="" npm publish --access public --verbose --@sinc-gmbh:registry=https://registry.npmjs.org
        working-directory: lib
